[build]
  command = "echo 'No build command required'"
  publish = "/"

[identity]
  # This tells Netlify to use our special pages for confirmation and recovery.
  # This is the FIX for the broken email links.
  [identity.templates]
    confirmation = "/admin/invite.html"
    recovery = "/admin/invite.html"

[git-gateway]