# This file gives direct instructions to Netlify's build system.

[build]
  # For a static HTML/CSS/JS site, the publish directory is the root.
  publish = "/"

# This section explicitly enables the Netlify Identity service (the login system).
[identity]

# This section explicitly enables the Git Gateway service, which allows
# the admin panel to connect to your GitHub repository.
[git-gateway]