backend:
  name: git-gateway
  branch: main

media_folder: "assets/images/uploads"
public_folder: "/assets/images/uploads"

collections:
  - name: "test_pages"
    label: "Test Pages"
    folder: "content/test"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}