# Specifies how Netlify CMS connects to your repository.
backend:
  name: git-gateway
  branch: main # The branch to publish changes to

# Specifies where to store uploaded images and their public URL path.
media_folder: "assets/images/uploads"
public_folder: "/assets/images/uploads"

# "Collections" are the types of content you can edit.
collections:
  # Collection 1: A single file to manage content on the Homepage.
  - name: "pages"
    label: "Page Content"
    files:
      - file: "content/homepage.json"
        label: "Homepage"
        name: "homepage"
        fields:
          - {label: "Welcome Section Title", name: "welcome_title", widget: "string"}
          - {label: "Welcome Section Subheading", name: "welcome_subheading", widget: "string"}
          - {label: "Welcome Section Body Text", name: "welcome_text", widget: "text"}
  
  # Collection 2: A folder of properties for the "BUY" page.
  - name: "properties"
    label: "Properties"
    folder: "content/properties" # Where to store the property files
    create: true # Allow users to create new properties
    slug: "{{slug}}" # The filename will be based on the title
    fields: # The fields for each property
      - {label: "Property Name", name: "title", widget: "string"}
      - {label: "Location Name (e.g., Dubai Marina)", name: "location_name", widget: "string"}
      - {label: "Location Slug (e.g., Dubai Marina or Al Mowaihat 2)", name: "location_slug", widget: "string"}
      - {label: "Status", name: "status", widget: "select", options: ["Ready to Move", "Off-Plan"]}
      - {label: "Price (Numbers only, no commas)", name: "price", widget: "number"}
      - {label: "Main Image", name: "image", widget: "image"}
      - {label: "Beds", name: "beds", widget: "number", default: 1}
      - {label: "Baths", name: "baths", widget: "number", default: 1}
      - {label: "Area (sqft)", name: "area", widget: "number", default: 1000}
      - {label: "Description", name: "description", widget: "markdown"}