backend:
  name: git-gateway
  branch: main

media_folder: "assets/images/uploads"
public_folder: "/assets/images/uploads"

collections:
  - name: "content"
    label: "Website Content"
    files:
      - label: "Homepage"
        name: "homepage"
        file: "_data/homepage.json"
        fields:
          - {label: "Welcome Section Title", name: "welcome_title", widget: "string", default: "Welcome to Koush"}
          - {label: "Welcome Section Subheading", name: "welcome_subheading", widget: "string", default: "Over 10 Years of Excellence"}
          - {label: "Welcome Section Body Text", name: "welcome_text", widget: "text"}
      - label: "Properties"
        name: "properties"
        file: "_data/properties.json"
        fields:
          - label: "Property Listings"
            name: "items"
            widget: "list"
            fields:
              - {label: "Property Name", name: "title", widget: "string"}
              - {label: "Slug (URL-friendly name, e.g., the-one)", name: "slug", widget: "string"}
              - {label: "Location Name", name: "location_name", widget: "string"}
              - {label: "Status", name: "status", widget: "select", options: ["For Sale", "For Rent", "For Investment"]}
              - {label: "Price (Numbers only)", name: "price", widget: "number"}
              - {label: "Main Image (for grid view)", name: "image", widget: "image"}
              - {label: "Beds", name: "beds", widget: "number", default: 1}
              - {label: "Baths", name: "baths", widget: "number", default: 1}
              - {label: "Area (sqft)", name: "area", widget: "number", default: 1000}
              - {label: "Overview (long description)", name: "overview", widget: "markdown"}
              - {label: "Image Gallery (add multiple photos)", name: "gallery", widget: "list", field: {label: Image, name: image, widget: image}}
              - {label: "Features (add multiple points)", name: "features", widget: "list", field: {label: Feature, name: feature, widget: string}}
              - {label: "Amenities (add multiple tags)", name: "amenities", widget: "list", field: {label: Amenity, name: amenity, widget: string}}